# Generated by Django 4.1.4 on 2022-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_proyectos_tags_proyectos_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyectos",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
